language: go
go:
  - 1.2
  - 1.3
  - 1.4
  - tip

sudo: false

before_install:
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get github.com/bitly/go-simplejson
  - go get golang.org/x/net/publicsuffix
  - go get golang.org/x/net/proxy
  - go get github.com/bmizerany/assert

install:
  - go build

script:
  - echo "test.txtabc" > test.txt
  - $HOME/gopath/bin/goveralls -repotoken BB7TANeKBvI1vunBdOQSxseNkSQxDW2dz
